apiVersion: v1
kind: Deployment
metadata:
  name: customer-service
spec:
  template:
    spec:
      containers:
        - env:
            - name: DB_USERNAME
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: user
            - name: DB_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: password
            - name: DB_PORT
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: databaseServicePort
            - name: DB_NAME
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: databaseName
            - name: DB_HOST
              valueFrom:
                 secretKeyRef:
                   name: my-database-secret
                   key: databaseServiceHost