metadata:
  labels:
    project: spring-petclinic-customers-service
    version: 1.5.9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: spring-petclinic-customers-service
        version: 1.5.9