metadata:
  name: customer-service
  labels:
    project: customer-service
    version: 1.5.9
spec:
  replicas: 1
  template:
    metadata:
      labels:
        project: customer-service
        version: 1.5.9
    spec:
      containers:
      - env:
        - name: DB_USERNAME
          valueFrom:
             secretKeyRef:
               name: customer-db-creds
               key: user
        - name: DB_PASSWORD
          valueFrom:
             secretKeyRef:
               name: customer-db-creds
               key: password
        - name: DB_PORT
          valueFrom:
             secretKeyRef:
               name: customer-db-creds
               key: databaseServicePort
        - name: DB_NAME
          valueFrom:
             secretKeyRef:
               name: customer-db-creds
               key: databaseName
        - name: DB_HOST
          valueFrom:
             secretKeyRef:
               name: customer-db-creds
               key: databaseServiceHost
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
      volumes:
      - name: hawkular-openshift-agent
        configMap:
          name: customer-service-metrics-config
      